### ISSUE TITLE
Migrate repository to aboutcode-org

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/scancode.io#1350]
Procedures:

- [x] Announce on Gitter/Element, in a specific channel if available, to notify of the org migration process including the scheduled start time and the expected completion time.
- [ ] Follow the following procedures instruction for the org migration process
  - [x] 1. Transfer the nexB repo to the aboutcode-org organization from Settings -> Danger Zone -> Transfer ownership
  - [ ] 2. Set up CI for that repo on Azure Devops
    * Log into the nexB organization on Azure Devops
    * Go to the project that was moved
    * On the left hand menu, click on Pipelines, and then delete the existing pipeline
    * On the same page, click New pipeline, and then click Github, then select the repo that was transferred to aboutcode-org
    * Complete adding the pipeline
- [x] Announce on Gitter/Element, in a specific channel if available, to notify the completion of the org migration.
- [x] Update org-level permissions: Check org-level permissions for the source repo and update the repo-level permissions on the migrated repo
- [x] Check if there are any old references with the previous org (documentation, reference links) that need to be updated.
- [ ] Push a new release about the org change with the updated references

**Comment by tdruez** [comment]
@chinyeungli What's the impact on the code env of the developers? Current branches, PR, issues references in the codebase, etc...?

**Comment by chinyeungli** [comment]
@tdruez To the best of my knowledge, all the issues, pull requests, and branches will be smoothly transferred to the new ownership without any issues. Some users might encounter a "Permission denied error on GitHub Push" following the migration if they have a generic password saved. However, this can be resolved by removing it and re-entering the password. See (https://stackoverflow.com/questions/17857283/permission-denied-error-on-github-push)

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository
All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:
```
git remote set-url origin NEW_URL
```

**Comment by tdruez** [comment]
@chinyeungli Thanks for the precisions 👍

**Comment by chinyeungli** [comment]
This repo doesn't use Azure Devops

**Comment by chinyeungli** [comment]
pull request created: https://github.com/aboutcode-org/scancode.io/pull/1362

I updated the CHANGELOG and the changes will be pushed along with the next release.
