### ISSUE TITLE
Android APK D2D: Map converted JARs to Java source code

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode.io#1373]
This is a mapping step in the map deployed to devel that should take place after extraction from classes.dex and similar.

**Comment by JonoYang** [comment]
In the android_inspector android apk d2d pipeline, we call jadx on classes.dex files from extracted apks and jars and then perform path matching of the jadx output on the source codebase.

**Comment by pombredanne** [comment]
This is merged with #1391 which adds the new android-inspector pipeline to SCIO. See:
- https://github.com/aboutcode-org/android-inspector
- https://github.com/aboutcode-org/android-inspector/blob/main/src/android_inspector/pipelines/android_d2d.py
