### ISSUE TITLE
Typo mistakes in ScanCode.io Official Documentation

### ISSUE THREAD

**Issue by VarshaUN** [aboutcode-org/scancode.io#1386]
While I was going through documentation of ScanCode.io I found Three typo mistakes as follows

![Screenshot (47)](https://github.com/user-attachments/assets/4694336e-c290-4eaf-b1a0-c323500da38c)

![Screenshot (45)](https://github.com/user-attachments/assets/48af568d-fb42-489a-893f-8a4fe72dbed3)

![Screenshot (44)](https://github.com/user-attachments/assets/cc2051d7-c5fd-449a-8a2c-8a326e20034e)

I have raised a PR please look into it.

**Comment by pombredanne** [comment]
This has been merged! Thank you ++ :bow: :heart:
