### ISSUE TITLE
Compliance Alert section does not show up in Web UI

### ISSUE THREAD

**Issue by brittneyq** [aboutcode-org/scancode.io#1415]
**Describe the bug**
In the [documentation](https://scancodeio.readthedocs.io/en/latest/tutorial_license_policies.html#how-does-the-compliance-alert-work), it says the compliance alert should be displayed in the Web UI. After talking to Philippe, he said that section should show up in all cases, but I am unable to see it for any project.

**System configuration**
- Which version of ScanCode.io are you running? 34.8.1
- What inputs are you using? docker image tags for analyze_docker_image pipeline; our main repo's tar.gz for inspect_packages & populate_purldb pipeline; source tar.gz tomcat bundle, liferay-scio-automation.tar.gz, & scancode.config.yml for map_deploy_and_develop pipeline
- Which pipeline are you running? analyze_docker_image, inspect_packages, populate_purldb, map_deploy_and_develop

**To Reproduce**
1. Go to a Scancode Project that ran a pipeline.
2. Scroll and look for the compliance alert section.

**Expected behavior**
I expect to see a compliance alert section such as :
![image](https://github.com/user-attachments/assets/1ea6b8fc-0c9f-4558-bf69-ef122b99bd9c)
or something to indicate whether compliance errors exists within the UI.

**Screenshots**
Examples of projects:
inspect_packages and populate_purldb:
![image](https://github.com/user-attachments/assets/53f7729a-7294-48a9-a71f-89930794c14c)
![image](https://github.com/user-attachments/assets/214b768e-4f86-414a-8f15-a7b3826a0f0b)
analyze_docker_image:
![image](https://github.com/user-attachments/assets/ba84fc16-07b4-4337-9b31-2614776d1790)
map_deploy_to_develop:
![image](https://github.com/user-attachments/assets/efdb6076-3216-4f29-8d09-8f82be427d29)

**Comment by tdruez** [comment]
Hi @brittneyq new features from https://github.com/aboutcode-org/scancode.io/issues/1346#issuecomment-2442245348

> A new Compliance panel in the project details view was added in #1417
Documentation available at https://scancodeio.readthedocs.io/en/latest/tutorial_license_policies.html#web-ui
> The compliance alerts are now available in the CLI, UI, and REST API.
I'm closing this one as done. Let's create new issues for further improvements.

**Comment by brittneyq** [comment]
Thanks @tdruez !
