### ISSUE TITLE
Add a live endpoint to find vulnerabilities in a dependency tree

### ISSUE THREAD

**Issue by TG1999** [aboutcode-org/scancode.io#1447]
We can use python-inspector and point towards vulnerable packages in a dependency tree.

Reported by @pombredanne

**Comment by AyanSinhaMahapatra** [comment]
With https://github.com/aboutcode-org/scancode.io/issues/1066 we now have the models required to store dependency tree information and the `find_vulnerabilities` pipeline looks for vulnerabilities in those dependencies/resolved packages.
