### ISSUE TITLE
In the API, enable to filter the packages of a project by PURL

### ISSUE THREAD

**Issue by AnotherDaniel** [aboutcode-org/scancode.io#1449]
When using the REST API, it would be useful to be able to filter project packages by PURL, like this:

`http://localhost:8001/api/projects/<uuid>/packages/?purl=pkg:cargo/json@0.12.4`

**Comment by tdruez** [comment]
@AnotherDaniel thanks for the suggestion, added in https://github.com/aboutcode-org/scancode.io/pull/1450

**Comment by AnotherDaniel** [comment]
Wow that was fast, thanks!
