### ISSUE TITLE
[UI improvement] Make the heading row of the tables frozen/sticky 

### ISSUE THREAD

**Issue by silverhook** [aboutcode-org/scancode.io#1457]
The Packages/Dependencies/Resources/… views in the webUI have large tables.

Which is fine, as long as you are at the top of the table:
![image](https://github.com/user-attachments/assets/2dbcc1ac-db53-49e0-954f-f223d74bc196)

But as soon as you scroll down a bit, it quickly becomes gobbledygook: 

![image](https://github.com/user-attachments/assets/841e0dd0-4f44-4be0-abe3-e9621719d0cd)

What is true? What is false? What does it all mean? :anguished: 

I propose that for every table in the webUI the heading row is made frozen/sticky/anchored – so when you scroll down the table, the header still stay there and provides the needed reference.

This issue was noted to exist both on Firefox and Chromium, so I assume it is not a browser issue.

**Comment by tdruez** [comment]
@silverhook Thanks for the suggestion. Added in https://github.com/aboutcode-org/scancode.io/pull/1458/

**Comment by silverhook** [comment]
Thank you, @tdruez
