### ISSUE TITLE
Move for_packages field in SCIO XLSX output

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode.io#1487]
When analyzing RESOURCES from a Scan one of the most common questions is how many Resources are from a package because these are Resources that normally do not require further analysis. The enhancement request is to update the XLSX output to move the `for_packages` field to the left - between `status `and `tag`.

**Comment by tdruez** [comment]
Done in https://github.com/aboutcode-org/scancode.io/pull/1489

**Comment by mjherzog** [comment]
Thank you!
